
enum PacketType
{
	ERROR1 = -1,
	POSITIONROTATION = 3,
	POSITION = 4,
	COMPONENTPOSITION = 5,
	ITEMPOSITION = 6,
	ITEMSPAWN = 7,
	COMPONENTDROPPED = 8,
	ITEMDROPPED = 9,
	PACKETID = 10,
	WINNER = 11,
	LOSER = 12,
	SPAWNCOMPONENT = 13,
	SPACESHIPPOSITION = 14,
	COMPONENTADDED = 15,
	COMPONENTREQUESTINGPICKUP = 16,
	ITEMPICKEDUP = 17,
	COMPONENTCONFIRMEDPICKUP = 18,
	COMPONENTPOSITIONNEW = 19,
	PLAYERHIT = 21,
	PLAYERID = 22,
	BASEBALLBATSPAWN = 23,
	POTIONSPAWN = 24
	SPAWNPLANETS = 25
};
