
enum PacketType
{
	ERROR1 = -1,
	POSITIONROTATION = 3,
	POSITION = 4,
	COMPONENTPOSITION = 5,
	ITEMPOSITION = 6,
	ITEMSPAWN = 7,
	COMPONENTDROPPED = 8,
	PACKETID = 10,
	WINNER = 11,
	LOSER = 12,
	SPAWNCOMPONENT = 13,
	SPACESHIPPOSITION = 14,
	COMPONENTADDED = 15,
	PLAYERHIT = 21
};

